version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app_net
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks:
      - app_net
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

networks:
  app_net:
    driver: overlay

volumes:
  mongo_data:
